/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wordpress_jdevel_utils_JAccessTimeUnix */

#ifndef _Included_com_wordpress_jdevel_utils_JAccessTimeUnix
#define _Included_com_wordpress_jdevel_utils_JAccessTimeUnix
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_wordpress_jdevel_utils_JAccessTimeUnix_getLastAccessTime
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
